package br.digitalmenu.view;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import br.digitalmenu.dao.UsuarioDAO;
import br.digitalmenu.heuristicas.Heuristica;
import br.digitalmenu.model.Usuario;
import java.awt.Component;
import java.awt.Font;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;

public class TelaUsuarios extends Heuristica {

    public TelaUsuarios() throws SQLException {
        initComponents();

        //DefaultTableModel modelo = (DefaultTableModel) tblListaUsuarios.getModel();
        //tblListaUsuarios.setRowSorter(new TableRowSorter(modelo));
        //ListaTabela();
        //muda a cor do cabecalho e aumenta a fonte do header na classe heuristica
        tblListaUsuarios.getTableHeader().setDefaultRenderer(new CorDoCabecalho());//Muda cor do header na classe heuristica

        IniciaTabela(tblListaUsuarios);//Formata a tabela e centraliza pela classe heuristicas
        ListaTabela();
    }

    public void ListaTabela() throws SQLException {
        DefaultTableModel model = (DefaultTableModel) tblListaUsuarios.getModel();
        model.setNumRows(0);

        UsuarioDAO usuarios = new UsuarioDAO();
        for (Usuario UsuarioLocal : usuarios.listaTodosOsUsuarios()) {

            model.addRow(new Object[]{
                UsuarioLocal.getIdusuario(),
                UsuarioLocal.getUsuario(),
                UsuarioLocal.getSenha(),
                UsuarioLocal.getTipoacesso(),
                UsuarioLocal.getStatus(),});
        }
    }

    public void Limpar() {

        ((DefaultTableModel) tblListaUsuarios.getModel()).setRowCount(0);
        // Limpando campos Text
        txtUsuario.setText("");
        txtSenha.setText("");
        rdoGrupo1.clearSelection();
        //Deixando o focu no primeiro campo
        txtUsuario.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdoGrupo1 = new javax.swing.ButtonGroup();
        pnlGlobal = new javax.swing.JPanel();
        pnlTabelaConsulta = new javax.swing.JScrollPane();
        tblListaUsuarios = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        btnAdicionar = new javax.swing.JButton();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtSenha = new javax.swing.JTextField();
        lblSenha = new javax.swing.JLabel();
        lblTipoAcesso = new javax.swing.JLabel();
        btnDesativar = new javax.swing.JButton();
        rdoPadrao = new javax.swing.JRadioButton();
        btnAtivar = new javax.swing.JButton();
        rdoAdmin = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Usuários");
        setPreferredSize(new java.awt.Dimension(1360, 859));

        pnlGlobal.setBackground(new java.awt.Color(255, 255, 255));

        pnlTabelaConsulta.setBackground(new java.awt.Color(246, 242, 233));

        tblListaUsuarios.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        tblListaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Usuário", "Senha", "Tipo de Acesso", "Status"
            }
        ));
        tblListaUsuarios.setRowHeight(30);
        pnlTabelaConsulta.setViewportView(tblListaUsuarios);

        jPanel5.setBackground(new java.awt.Color(246, 242, 233));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Controle de Usuários", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        btnAdicionar.setBackground(new java.awt.Color(255, 243, 198));
        btnAdicionar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblUsuario.setText("Usuário");

        txtUsuario.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        txtSenha.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        lblSenha.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblSenha.setText("Senha");

        lblTipoAcesso.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblTipoAcesso.setText("Tipo de acesso:");

        btnDesativar.setBackground(new java.awt.Color(255, 153, 153));
        btnDesativar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnDesativar.setText("Desativar");
        btnDesativar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesativarActionPerformed(evt);
            }
        });

        rdoGrupo1.add(rdoPadrao);
        rdoPadrao.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        rdoPadrao.setText("Atendente");

        btnAtivar.setBackground(new java.awt.Color(204, 255, 204));
        btnAtivar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnAtivar.setText("Ativar");
        btnAtivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtivarActionPerformed(evt);
            }
        });

        rdoGrupo1.add(rdoAdmin);
        rdoAdmin.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        rdoAdmin.setText("Administrador");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTipoAcesso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdoAdmin)
                        .addGap(18, 18, 18)
                        .addComponent(rdoPadrao)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, Short.MAX_VALUE)
                .addComponent(btnAtivar, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDesativar, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenha)
                    .addComponent(lblUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSenha)
                            .addComponent(txtUsuario)
                            .addComponent(btnAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTipoAcesso)
                            .addComponent(rdoAdmin)
                            .addComponent(rdoPadrao))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDesativar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAtivar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))))
        );

        javax.swing.GroupLayout pnlGlobalLayout = new javax.swing.GroupLayout(pnlGlobal);
        pnlGlobal.setLayout(pnlGlobalLayout);
        pnlGlobalLayout.setHorizontalGroup(
            pnlGlobalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlGlobalLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlGlobalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTabelaConsulta))
                .addGap(14, 14, 14))
        );
        pnlGlobalLayout.setVerticalGroup(
            pnlGlobalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGlobalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlTabelaConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlGlobal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlGlobal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1394, 807));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtivarActionPerformed
        if (tblListaUsuarios.getSelectedRow() != -1) {
            int confirma = JOptionPane.showConfirmDialog(
                this,
                "Deseja confirmar a ativação do usuário " + String.valueOf(tblListaUsuarios.getValueAt(tblListaUsuarios.getSelectedRow(), 0).toString()) + "?",
                "Confirmar ativação?",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
            );
            if (confirma == JOptionPane.YES_OPTION) {
                try {
                    UsuarioDAO userDAO = new UsuarioDAO();
                    Usuario user = new Usuario();

                    //fazendo a chamada do metodo para buscar por id
                    userDAO.buscaPorID((Integer.parseInt(tblListaUsuarios.getValueAt(tblListaUsuarios.getSelectedRow(), 0).toString())), user);
                    user.setStatus("ATIVADO");//######ATIVA O USUARIO#####
                    userDAO.atualizaUsuario(user);//chama o metodo de atualizacao
                    JOptionPane.showMessageDialog(null, "Usuário desativado com sucesso!");
                    Limpar();
                    ListaTabela();

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Erro: " + e.getMessage());
                }
            } else if (confirma == JOptionPane.NO_OPTION) {
                JOptionPane.showMessageDialog(null, "Operacão cancelada.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um usuário para excluir.");
        }
    }//GEN-LAST:event_btnAtivarActionPerformed

    private void btnDesativarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesativarActionPerformed
        if (tblListaUsuarios.getSelectedRow() != -1) {
            int confirma = JOptionPane.showConfirmDialog(
                this,
                "Deseja confirmar a desativação do usuário " + String.valueOf(tblListaUsuarios.getValueAt(tblListaUsuarios.getSelectedRow(), 0).toString()) + "?",
                "Confirmar desativação?",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
            );
            if (confirma == JOptionPane.YES_OPTION) {
                try {
                    UsuarioDAO userDAO = new UsuarioDAO();
                    Usuario user = new Usuario();

                    //fazendo a chamada do metodo para buscar por id
                    userDAO.buscaPorID((Integer.parseInt(tblListaUsuarios.getValueAt(tblListaUsuarios.getSelectedRow(), 0).toString())), user);
                    user.setStatus("DESATIVADO");//######DESATIVA O USUARIO#####
                    userDAO.atualizaUsuario(user);//chama o metodo de atualizacao
                    JOptionPane.showMessageDialog(null, "Usuário desativado com sucesso!");
                    Limpar();
                    ListaTabela();

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Erro: " + e.getMessage());
                }
            } else if (confirma == JOptionPane.NO_OPTION) {
                JOptionPane.showMessageDialog(null, "Operacão cancelada.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um usuário para excluir.");
        }
    }//GEN-LAST:event_btnDesativarActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed

        Usuario user = new Usuario();

        try {
            String usuario;
            String tipoAcesso = null;
            String senha;

            boolean campo1 = this.verificarSeCampoEstaEmBranco(txtUsuario, "Usuário");
            boolean campo2 = verificarSeCampoEstaEmBranco(txtSenha, "Senha");

            if (campo1 && campo1) {
                if (rdoGrupo1.getSelection() == null) { //se os tipos de acessos estiverem vazios
                    JOptionPane.showMessageDialog(null, "Escolha o tipo de acesso!");
                    txtSenha.requestFocus();
                } else {
                    if (rdoAdmin.isSelected()) {
                        tipoAcesso = "administrador";
                    }

                    if (rdoPadrao.isSelected()) {
                        tipoAcesso = "atendente";
                    }

                    usuario = txtUsuario.getText();
                    usuario = usuario.toLowerCase();//faz o usuario ficar em letras minusculas

                    senha = txtSenha.getText();

                    user.setUsuario(usuario);
                    user.setSenha(senha);
                    user.setTipoacesso(tipoAcesso);
                    String status = "ativado";//##### COMO PADRÃO, O USUARIO SERÁ CRIADO ATIVADO  ######
                    user.setStatus(status);

                    UsuarioDAO userDAO = new UsuarioDAO();

                    userDAO.insereUsuario(user);
                    JOptionPane.showMessageDialog(null, "Usuário cadastrado com sucesso!");

                    Limpar();
                    ListaTabela();
                }
            }

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnAdicionarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnAtivar;
    private javax.swing.JButton btnDesativar;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTipoAcesso;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlGlobal;
    private javax.swing.JScrollPane pnlTabelaConsulta;
    private javax.swing.JRadioButton rdoAdmin;
    private javax.swing.ButtonGroup rdoGrupo1;
    private javax.swing.JRadioButton rdoPadrao;
    private javax.swing.JTable tblListaUsuarios;
    private javax.swing.JTextField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
